### ISSUE TITLE
您好，使用了您发布的最新程序时发现了好像缺少指南针正对位置左侧时的两帧图像

### ISSUE THREAD

**Issue by Asukapipi** [chaosgoo/mcompass#2]
<img width="277" alt="1" src="https://github.com/user-attachments/assets/5ab8b8b2-33ac-4a8b-9179-01a69ceb33b3" />
<img width="278" alt="2" src="https://github.com/user-attachments/assets/e68506e0-1749-4fb9-9371-a006149ab9a7" />

**Comment by chaosgoo** [comment]
我检查了一下取模的原始素材,发现确实少了右边那张图像.待我修复

**Comment by Asukapipi** [comment]
您好，只有右边那一张吗🤔？我仔细观察后发现左侧那一张应该也是缺少的，看红色色块可能会混淆，可以观察白色色块，罗盘正中图像左侧第二张应该有白色色块四个，希望能再核查一下☺️> 我检查了一下取模的原始素材,发现确实少了右边那张图像.待我修复

**Comment by chaosgoo** [comment]
> 您好，只有右边那一张吗🤔？我仔细观察后发现左侧那一张应该也是缺少的，看红色色块可能会混淆，可以观察白色色块，罗盘正中图像左侧第二张应该有白色色块四个，希望能再核查一下☺️> 我检查了一下取模的原始素材,发现确实少了右边那张图像.待我修复

显示画面缺少这两帧画面是逻辑问题, 而取模素材的确是缺少了右边的那一张. 已修复此问题.
