### ISSUE TITLE
您好，单按钮在已知硬件下应该还能实现多种丰富的功能吧

### ISSUE THREAD

**Issue by Asukapipi** [chaosgoo/mcompass#3]
1. **单击**：轻按一次按钮，切换gps模式和指南模式。
2. **双击**：可在网页中设置多个需要定位地址，以开头闪烁红橙黄绿青蓝紫来提示是第几个坐标，快速连续按两次按钮，用于切换使用不同坐标。
3.**按压时间检测**：根据按住的时间长短执行不同的操作，比如：
按住 1-3 秒：用于绑定当前所在地为指向位置。
按住 >5 秒：重置WiFi信息，这样就不用找数据线了。
4.**有关gps的问题**：gps在室外链接完成以后在部分室内可以正常使用，但在室内开机却搜寻不到信号，是否可以存在室外搜寻到信号，保持低功率待机模式，再在室内启用正常使用，使其不需要再出去接受信号
（本人没什么编程的经验但自制使用了几天后希望这款指南针能实现更多功能，希望博主能够采纳(*^▽^*)）

**Comment by chaosgoo** [comment]
> 1. **单击**：轻按一次按钮，切换gps模式和指南模式。
> 2. **双击**：可在网页中设置多个需要定位地址，以开头闪烁红橙黄绿青蓝紫来提示是第几个坐标，快速连续按两次按钮，用于切换使用不同坐标。
>    3.**按压时间检测**：根据按住的时间长短执行不同的操作，比如：
>    按住 1-3 秒：用于绑定当前所在地为指向位置。
>    按住 >5 秒：重置WiFi信息，这样就不用找数据线了。
>    4.**有关gps的问题**：gps在室外链接完成以后在部分室内可以正常使用，但在室内开机却搜寻不到信号，是否可以存在室外搜寻到信号，保持低功率待机模式，再在室内启用正常使用，使其不需要再出去接受信号
>    （本人没什么编程的经验但自制使用了几天后希望这款指南针能实现更多功能，希望博主能够采纳(_^▽^_)）

1.这个功能已经做加入过了
2.考虑中
3.本来就有这个长按绑定，超过5s的重置Wi-Fi和长时间连接不上Wi-Fi长按重置功能重复了
4.低功耗没有想象的那么好做

**Comment by Asukapipi** [comment]
已知有的功能都体验过了。
关于第三点，重置wifi信息是需要链接电脑下启动，然后在绿色wifi链接状态下长按按钮。若要修改定位消息也需要插上线才能进入连接wifi模式。但是进入wifi模式以后再拔掉电源线以后仍在链接wifi模式下任可以正常访问设置网站，插线启动应该不是必要条件，应该能省略在按键中。这是我的意思，希望能够参考😘

**Comment by chaosgoo** [comment]
考虑以后用蓝牙来配置，Wi-Fi相关内容会废弃，所以暂时不做修改。
